### ISSUE TITLE
Please add feed detection on websites

### ISSUE THREAD

**Issue by Riotous** [aureliendavid/rsspreview#11]
RSSPreview is really nice. It has the best preview formatting of any RSS extension I've seen, but it's missing one vital thing to make it complete. There's no way to tell whether a website has a feed or not, so you don't even know if there's anything to preview in the first place. The user has to experiment with URLs just to find out the feed URL in order to even use this extension. I think feed previewing needs detection in order to be useful in the first place because it works as the bridge between the website and the preview this extension renders. 

I suggest you add simple feed detection where an icon shows up in the address bar if a feed is detected, and clicking on that icon takes you to the feed preview with the URL in the address bar. Nothing else is needed after that. No livemarks are needed. Perfection achieved.

**Comment by Riotous** [comment]
@somini I suppose that does work the way I wanted it to. 

If only both these projects got merged into one.  It seems like they need each other to be complete.

**Comment by Jimmy03** [comment]
Is feedburner working with RSSPreview?

**Comment by aureliendavid** [comment]
@Riotous 

I might add feed detection if I find the time to do it and it doesn't bloat the extension too much. I don't use that feature so it hasn't been my priority but since a few people have asked for it I'll see what I can do

@Jimmy03 

feedburner feeds have their own xsl stylesheet that basically does the same thing as the extension, so they present as already formed html pages and we don't reparse them (firefox <64 did the same thing)

**Comment by sojusnik** [comment]
Add-ons like [this](https://addons.mozilla.org/de/firefox/addon/feed-preview/), [this](https://addons.mozilla.org/de/firefox/addon/feed-indicator/) and [this](https://addons.mozilla.org/de/firefox/addon/want-my-rss/) also combine the preview functionality with feed detection. Since this add-on has, imho, the best layout, it would certainly benefit from feed detection too.

**Comment by Riotous** [comment]
> Since this add-on has, imho, the best layout
That's precisely why I went with rsspreview and was dismayed at the lack of feed detection. How was I supposed to preview the feed? Guessing the URL? That's why feed detection and preview can't be mutually exclusive.

**Comment by Riotous** [comment]
@aureliendavid That's fair and I also use your addon for podcasts but you have to admit, having your addon show me the link to the preview rather than googling or using "view source" is much quicker and handier. It also gives your addon a nice, minimal visual cue on the browser than there not being one at all outside of the extensions page.

**Comment by aureliendavid** [comment]
Hi all, 

I pushed a v3.0 that adds basic feed detection, with some limitations: 

1. it's disabled by default, you'll need to enable it in the addon options ; this is because this feature is not very tested yet, and I also don't want to clutter people's address bar with an additional icon if they don't want it

2. it only works on sites that properly declare their feeds with something like 

`<link rel="alternate" type="application/rss+xml" href="..." />`

It looks like a lot of sites don't bother to do that anymore (including a lot of podcast pages), in that case I can't really do anything. 

3. the popup menu that opens when clicking the address bar button is ugly ; but for now it will be enough for a list of links

Other than that it should work. Unless it doesn't work at all for you, please open separate issues for specific problems about detection. 

thanks

**Comment by Riotous** [comment]
@aureliendavid Thanks for 3.0 feed detection. It works well on my sites so far, and good choice of icon in the URL bar! Very clean, and very thoughtful of you to make it optional. The popup menu isn't really that ugly, but I'm sure you can make it look better over time. You have the best looking preview page so I'm sure you will eventually make it look great. I'll be sure to open separate issues for detection. The best thing about this is that I don't need 2 extensions anymore! Thanks again!
