### ISSUE TITLE
Missing "media:thumbnail" images

### ISSUE THREAD

**Issue by lassana** [aureliendavid/rsspreview#12]
YouTube and some other feeds provide image preview for feed entries in the [`media:thumbnail`](http://www.rssboard.org/media-rss#media-thumbnails) tag. As I remember the original Firefox RSS previewer was able to display it. It would be nice if you could clone that behavior. 

The example: https://www.youtube.com/feeds/videos.xml?channel_id=UCTH6s1SMIQicvyd8OLBYMtQ

```
<entry>
  ...
  <media:group>
   ...
   <media:thumbnail url="https://i2.ytimg.com/vi/e9DfSCk-6Ko/hqdefault.jpg" width="480" height="360"/>
   ...
  </media:group>
 </entry>
```

**Comment by aureliendavid** [comment]
Hi @lassana 

It looks like it uses the [Media RSS](http://www.rssboard.org/media-rss) extension for RSS which has a whole syntax of its own. 

I checked with older versions of firefox and it doesn't look like it was supported: 

![oldff](https://user-images.githubusercontent.com/7168263/50645930-12a67580-0f75-11e9-832c-043010c2634f.png)
(this is firefox 46 & 63)

I didn't feel like supporting the whole thing and make it pretty, so I just added an img element to display the thumbnail when it exists: 

![thumbsfeed](https://user-images.githubusercontent.com/7168263/50646311-07077e80-0f76-11e9-8db2-89f0c938593c.PNG)

Might not be the best solution because some feeds will repeat the thumbnail in the `<content>` and other weird behaviors, but it should be good enough for a preview. 

Thanks for the report. Reopen the issue if there's a problem. 

(available from v2.5)

**Comment by roelandschoukens** [comment]
It seems some websites serve very large thumbnails (I’m encountering 1500px wide ones), which makes reading very awkward. A possible fix is applying a `max-width` to the images.

For example the Github blog → https://blog.github.com/blog.atom

**Comment by aureliendavid** [comment]
Hi @roelandschoukens 

I've added a `max-width` for all images to prevent very big images from messing things up

on the other hand, in the case of the github blog example, the big images aren't in `media:thumbnail` (as in the original issue) but in the `<content>` ; and if they decide to put big assets (other than images) in an entry's content, there's not much we can do here

anyway, I've set the max-width a bit arbitrarily at 900px in v2.6, please tell me if that works for you (and close the issue if it does, or open a separate issue if there are other problems)

thanks

**Comment by IoApo** [comment]
Hey all and congratulations for the fruitful feedback! 
If I can add to the discussion, may I suggest building a **"Preferences" / "Settings" page-panel**, where there could be an option (maybe just a **toggle-switch** button), in order to apply this modification? Indeed, the old firefox rss viewer did not had a support for `media:thumbnail` so it could be nice if we can have it as a non-mandatory feature, allowing the ability to opt-out. 

This could also help probably in some cases of building/developing a rss feed; a developer could do a quick check if `media:thumbnail` works well or not. Also, there are some feeds that include images both in `<content>` and in media:thumbnail tags; in that case the feed preview looks a bit bloated, as it seems like it show multiple images... 

So, a toggle-switch functionality may also make it easier to enable or disable the preview of `media:thumbnail` feature in the add-on!

**Comment by xyzcheese** [comment]
img {
width: 50% !important;
height: 50% !important;	
}
======================

I think this css would be ok. And customizing CSS should be also a good option.

**Comment by roelandschoukens** [comment]
Hi,

This is working for me 👍 .
