### ISSUE TITLE
Feeds ending in .rss get downloaded to windows temp

### ISSUE THREAD

**Issue by Jimmy03** [aureliendavid/rsspreview#13]
It might just be my Firefox setup, but feeds ending in .rss get downloaded to the windows temp folder and then opened into firefox from there rather than just loading in the browser automatically like other feeds.  
For example: https://www.buzzsprout.com/46291.rss  

Firefox treats it like a file type rather than a feed
  
I don't really want these rss files filling up windows temp

In the Applications section of Firefox options .rss files get set to 'save file' even after I try to set it back to default

**Comment by aureliendavid** [comment]
hm this is a bit weird

the decision to download or display in firefox is based on the content-type sent by the server, when it's something like `application/rss+xml` firefox will ask for download, when it's `text/xml` it will display the contents

there is a trick in the extension to force displaying rss feeds by changing the content-type sent by the server when it's not good - however it seems like this trick doesn't work all the time

the first case where it fails is when the feed is in the cache, since cached requests don't have their headers reprocessed, the trick doesn't work

in your case it looks like it fails because of a redirect - https://www.buzzsprout.com/46291.rss redirects to https://feeds.buzzsprout.com/46291.rss

when visiting that latter url (which also sends `application/rss+xml`), the trick works and the feed is displayed instead of downloaded - but when it's reached after a redirect it doesn't seem to work

i'll investigate further to see why that fails, in the meantime try to use the final urls if you can

thanks for the report

**Comment by aureliendavid** [comment]
Hi, 

This should now be fixed in v3.2. 

Reopen if needed.
