### ISSUE TITLE
Conflict with FDM extension

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [aureliendavid/rsspreview#17]
On [Wikimedia Commons](https://commons.wikimedia.org/wiki/Main_Page) this extension failed to load feeds if [Free Download Manager extension](https://addons.mozilla.org/firefox/addon/free-download-manager-addon/) is installed, the RSS file will be force download, unless you click Don't catch download from this site in FDM extension.

**Comment by aureliendavid** [comment]
Hi @KrasnayaPloshchad 

Thanks for the report. 

I was able to reproduce the issue, unfortunately I can't do anything about it. 

It has to do with how FDM catches files to download, and how wikimedia commons declares its rss feeds. 

Basically, the FDM extension catches everything that as a [content-disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) header as a file to download:

```js
// in dldsinterceptmgr.js

if (responseHeadersMap.has("content-disposition"))
{
    file = true;
}
...
        if (file)
        {
        ...
            this.onDownloadIntercepted(downloadInfo, details
            ...
```

The wikimedia feed at https://commons.wikimedia.org/w/api.php?action=featuredfeed&feed=motd&feedformat=atom for example sends back:

```
content-disposition: inline; filename="feed.xml"
```

The feed is a bit weird but I think the problem lies with the FDM extension. Having `inline` in the `content-disposition` header explicitly means that the content should be displayed in the browser and not downloaded as a file. 

So I think the FDM behavior is incorrect here. I don't know it they have a support page where bugs can be reported but I think this is one.

**Comment by KrasnayaPloshchad** [comment]
> So I think the FDM behavior is incorrect here. I don't know it they have a support page where bugs can be reported but I think this is one.

Go to their forum: http://www.freedownloadmanager.org/board/
