### ISSUE TITLE
Feedburner feeds look strange

### ISSUE THREAD

**Issue by Joel889** [aureliendavid/rsspreview#20]
Feedburner feeds are difficult to read and look nothing like the way they used to look in Firefox.

**Comment by aureliendavid** [comment]
feedburner feeds have their own xsl stylesheet and are displayed as html documents, so we don't touch them at all (they're not even detected as feeds by the extension) 

older firefox did the same thing so they should look exactly the same in old firefox and in newer firefox with the extension

reopen if you have a specific example where it's not the case

thanks

**Comment by Joel889** [comment]
> older firefox did the same thing so they should look exactly the same in old firefox and in newer firefox with the extension

That's not true in my experience. I guess I could install FF 63 in a virtual machine and send screenshots, but why not handle all rss feeds the same? Feedburner fees are difficult to read anyway.

**Comment by Joel889** [comment]
I just installed FF 60.5 esr. I tried all feedburner URL's from here:
https://news.ycombinator.com/item?id=18323512

Every single URL looks exactly like any other RSS feed. 
In FF 65 they look completly different.

**Comment by Joel889** [comment]
@aureliendavid 

I just installed FF 60.5 esr. I tried all feedburner URL's from here:
https://news.ycombinator.com/item?id=18323512

Every single URL looks exactly like any other RSS feed. 
In FF 65 they look completely different. 

Here are 3 screenshots:
https://imgur.com/a/M1CpaSc

**Comment by aureliendavid** [comment]
ah you're right, I misremembered what old firefox did, sorry about that

however that doesn't change the fact that the extension can't/won't work on feedburner feeds for the reason I mentioned above

since they contain their own xsl stylesheet, when opening a feedburner url, firefox transforms it into an html page before the extension even "sees" it ; the extension then sees a normal html page and doesn't detect it as an rss feed 

I don't know if there's a way to prevent that, but since the feedburner stylesheet does basically the same thing as the extension (albeit with a different visual style), it doesn't seem worth spending time on it just to achieve the same result, I find using the feedburner feeds as is sufficient

**Comment by Joel889** [comment]
@aureliendavid 
I'm leaving this here for reference in case you are interesting in fixing this in the future:

The following addon is detecting feedburner feeds. It is showing the RSS icon, and it makes the feed look the same as any other feed:
https://addons.mozilla.org/en-US/firefox/addon/feed-indicator/
