### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by delphipsmith** [aureliendavid/rsspreview#37]
I installed this and enabled it but nothing is happening.  How do I make it actually work?

**Comment by aureliendavid** [comment]
By default it just creates preview pages for rss feed, so when you visit a url of a feed (like https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml) it should display a preview page instead of a raw xml file. 

If you want it to detect feeds on websites you have to enable that feature in the addon options (about:addons > rsspreview > options > check "Enable feed detection"). Then when you visit a site with a feed (like https://www.nytimes.com/) it should add a button in the address bar with a link to the feed. 

Is that not working ?
