### ISSUE TITLE
Problem with html-codes eg. eacute

### ISSUE THREAD

**Issue by rular** [aureliendavid/rsspreview#39]
Hey, 

is this a bug or is it by design?

when I open my rssfeed, I get an error "undefined entity at row xxx column xx" and at this position is an "&eacute;" (haha, it's just showing an é but I mean an "& eacute ;"

did you encountered the same?

**Comment by aureliendavid** [comment]
do you have an example feed where this happens?

**Comment by rular** [comment]
Yes, try this one:

Http://bondage.dynns.com/bondage/Podcast10b.xml


Mit freundlichem Gruß

**Comment by aureliendavid** [comment]
Thanks. 

It looks like html entities (like `&eacute;`) aren't available in xml except for these 4: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML

It results in an invalid xml file and rsspreview can't do anything with it because the parser fails. 

You can replace `&eacute;` with `&#233;` for the same result but that produces a valid xml file. 

You can get the numerical codes here for example: https://www.w3schools.com/charsets/ref_html_entities_e.asp

**Comment by rular** [comment]
Yeah, tried that. But then, itunes won‘t be able to read this. Bcs another feed is released via itunes/apple - I had to turn all these special characters to normal ones. 

Fkn apple shit

Regards
