### ISSUE TITLE
Feed doesn't work

### ISSUE THREAD

**Issue by sojusnik** [aureliendavid/rsspreview#46]
It works in RSS Readers, but not with your add-on: https://blog.railcargo.com/newsfeed.xml

**Comment by aureliendavid** [comment]
the feed is a not-well-formed xml document that is rejected by firefox even before the addon has the chance to do anything (because of an unescaped `&`) 

there's nothing I can do about it, it's all firefox

the solution is for the site to fix their feed (without that one unescaped character the feed works well with the addon)
