### ISSUE TITLE
ecf.nyed.uscourts.gov RSS feed breaks rsspreview

### ISSUE THREAD

**Issue by johnhawkinson** [aureliendavid/rsspreview#68]
The RSS Feed for the Brooklyn federal district court https://ecf.nyed.uscourts.gov/cgi-bin/readyDockets.pl can break RSSpreview, returning this error:

```
XML Parsing Error: no root element found
Location: https://ecf.nyed.uscourts.gov/cgi-bin/readyDockets.pl
Line Number 8886, Column 1:
```

**At first I thought** ~I assume~ it's because it has a comment at or near the start of the XML:

```xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
 <!-- RSS generated by Eastern District of New York on Wed, 01 Sep 2021 00:40:02 GMT -->
 <rss version="2.0">
	<channel>
```

but then it magically started working. (And, I guess, in retrospect, that's nowhere near line 8886.)

Sorry this is a bad bug report.

I'm not entirely sure how to address this issue, but I'll note that the [Feed Preview addon](https://code.guido-berhoerster.org/addons/firefox-addons/feed-preview/) doesn't seem to have trouble with it.

Anyhow, if you have any tips for what I should do when this problem next recurr (other than saving a copy of the RSS output, duh!), let me know. I had…foolishly thought the problem was stable and would not go away with an update.

(Note that this particular federal court, the Eastern District of New York, has its own special RSS feed that's different from all other federal district court CM/ECF or PACER RSS feeds. If you're familiar with them.)

**Comment by aureliendavid** [comment]
Hi, 

thanks for the report. I haven't been able to reproduce the problem by trying to load the feed a few times (it seems to be working). 

The error you encountered looks like a page that has not loaded completely for some reason (a timeout maybe?) resulting in an invalid xml document. In this case rsspreview can't do anything since it relies on the browser for xml parsing and in this case it failed. 

If you encounter it again you can try saving the page you receive (ctrl+s), and saving its source (ctrl+u ctrl+s), and maybe checking the network request in the developer tools, and send what you get. 

But my guess is that it's an error from the server.

**Comment by johnhawkinson** [comment]
I don't think it was a server problem, because the error was consistently present with RSSpreview and consistently not present with Feed Preview…all until the feed updated.

Anyhow, I realize this bug report doesn't give you enough to do anything, so feel free to close it and I can reopen it if/when I have the actual reproducible case. Or leave it open, either way.

Sorry about that.

**Comment by aureliendavid** [comment]
haha no problem, I'd be curious to see what the problem was, so if it happens again feel free to reopen the issue and post whatever info you have

in any case, glad it's working now

have a good one
