### ISSUE TITLE
YouTube RSS feeds appear broken

### ISSUE THREAD

**Issue by miquelfire** [aureliendavid/rsspreview#79]
I rarely have a need to get the RSS feed of a channel, and when I went to get one recently, the feed I was getting was the wrong channel.

This is the channel I wanted the feed for: https://www.youtube.com/@StefanPerspective-yb1rm
This was the channel I was getting the feed for when I used the RSS button: https://www.youtube.com/@CeaveGaming
I'm not seeing the channel ID from @CeaveGaming in the source of @StefanPerspective-yb1rm (username might change)

I suspect this is using the video I just watched to get the channel ID (Ceave decided to split his content between two channels, hence the need to get the new RSS feed, and I haven't looked at a video on the new channel yet, in case the way this extension gets the channel ID is from the video I last watched)

I do see in the source that there is a `<link rel="alternate" type="application/rss+xml" title="RSS" href="...">` tag in the source of channel, but appears to be in the body tag in case that's something this extension needs to be mindful about

**Comment by aureliendavid** [comment]
I think this is a known issue, and I don't know if I can fix it, but it has an easy workaround:

What happens is that, on youtube, when you go from page to page, they don't actually reload your tab to a new url (like every other website does), but they load the new page in the current tab (you can see the red youtube loading bar on top of the page, instead of seing the browser loading bar). 

And since the page isn't fully loaded by the browser, the extension doesn't run for the new page. 

As a result, sometimes you don't see any rss being detected, or in your case you can see the one from the previous page.  

You can easily see if this is the case by just refreshing (F5) the youtube page where you want feeds to be detected. Or opening the link in a new tab (from the link in your post for example). Then it should detect the proper feed.

**Comment by sojusnik** [comment]
Any ideas why it fails on https://www.youtube.com/coldfusion or https://www.youtube.com/@ColdFusion/videos , although there's a working feed if you manually find out the channel id (https://www.youtube.com/feeds/videos.xml?channel_id=UC4QZ_LsYcvcq7qOsOhpAX4A), but generally works with other channels?
